version: 3

dotenv: ["maildebug.env", ".env"]

tasks:
    client:
        dir: ui
        cmds:
            - bun dev

    client:build:
        dir: ui
        cmds:
            - bun run build

    format:
        cmds:
            - bun run format

    server:
        cmds:
            - air

    test:
        dir: email-test
        cmds:
            - bun run send.tsx --email {{.CLI_ARGS}}
